# To run all unit tests inside data_structures from here:
# >>> python -m unittest discover
#
# Maybe there is a better way to to it, need to figure out...
#
# Also, not sure how to run single tests from here...
